linters:
  disable-all: true
  enable:
    - bodyclose # Checks whether HTTP response bodies are closed
    - errcheck # Checks error handling
    - gocritic # Provides many diagnostics
    - gocyclo # Checks cyclomatic complexity
    - gofmt # Standard Go formatting
    - gosec # Inspects source code for security problems
    - gosimple # Simplifies code
    - govet # Reports suspicious constructs
    - ineffassign # Detects ineffective assignments
    - misspell # Finds commonly misspelled words
    - revive # Replacement for golint
    - staticcheck # Advanced static analysis
    - typecheck # Like the front end of a Go compiler
    - unused # Checks for unused constants, variables, functions
run:
  deadline: 5m
issues:
  exclude-use-default: true
