linters:
  disable-all: true
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
run:
  deadline: 5m
issues:
  exclude-use-default: true
