repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, toml, markdown, javascript, ts, css, html, json]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args:
          - --fix
        exclude_types:
          - jupyter
      - id: ruff
        name: ruff (notebooks)
        args:
          - --fix
        types:
          - jupyter
      - id: ruff-format
        exclude_types:
          - jupyter
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: forbid-binary
      - id: shellcheck
      - id: shfmt
        stages: [pre-commit]
        args: ["-w", "-s", "-i", "4"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.3
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ["--args=--sort-by-required"]
  - repo: local
    hooks:
      - id: just
        name: just
        language: system
        entry: just --fmt --unstable
        files: ^justfile$
        pass_filenames: false
        types:
          - file
