repos:
  - repo: local
    hooks:
      - id: gofumpt
        name: gofumpt
        entry: docker run --rm -v $(pwd):/data -w /data qmcgaw/binpot:gofumpt
        language: system
        types: [go]
        args:
          - -w
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --ignore-path={{ outputFolder }}/.prettierignore --config={{ outputFolder }}/.prettierrc.json --write
        language: node
        types_or:
          - css
          - html
          - javascript
          - json
          - jsx
          - markdown
          - scss
          - ts
          - tsx
          - yaml
        additional_dependencies:
          - prettier@latest
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        name: ruff-check
        language: docker_image
        entry: ghcr.io/astral-sh/ruff
        args:
          - check
          - --fix
        files: '.*\.py$'
      - id: ruff-format
        name: ruff-format
        language: docker_image
        entry: ghcr.io/astral-sh/ruff
        args:
          - format
        files: '.*\.py$'
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: shellcheck
      - id: shfmt
        stages:
          - pre-commit
        args:
          - -w
          - -s
          - -i
          - "4"
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
        language: docker_image
      - id: terraform_docs
        language: docker_image
        args:
          - --args=--sort-by-required
  - repo: local
    hooks:
      - id: just
        name: just
        language: system
        entry: just --fmt --unstable
        files: ^justfile$
        pass_filenames: false
        types:
          - file
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        language: docker_image
        files: .github/workflows/
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
  - repo: https://github.com/instrumentl/pre-commit-just
    rev: v0.1
    hooks:
      - id: format-justfile
