repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        description: Detect hardcoded secrets using Gitleaks
        language: docker_image
        entry: zricethezav/gitleaks:latest
        args:
          - protect
          - --verbose
          - --redact
          - --staged
        stages:
          - pre-commit
  - repo: local
    hooks:
      - id: dclint
        name: dclint
        description: docker copose file linter
        language: docker_image
        entry: zavoloklom/dclint
        files: ^(docker-)?compose\.ya?ml$
        args: 
          - --verbose
          - --fix 
  - repo: local
    hooks:
      - id: hadolint
        language: docker_image
        name: Lint Dockerfiles (nested support)
        description: Runs hadolint via Docker to lint Dockerfiles at any directory depth
        files: (^|/)Dockerfile(\..+)?$
        require_serial: true
        verbose: true
        entry: hadolint/hadolint
        args:
          - hadolint
  - repo: local
    hooks:
      - id: gofumpt
        language: docker_image
        name: gofumpt
        description: Runs gofumpt on go files
        verbose: true
        entry: qmcgaw/binpot:gofumpt 
        types:
          - go
        args:
          - -w
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go
        language: docker_image
        entry: golangci/golangci-lint:v2.5.0
        args:
          - golangci-lint
          - run
          - --fix
        types:
          - go
        pass_filenames: false
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --ignore-path={{ outputFolder }}/.prettierignore --config={{ outputFolder }}/.prettierrc.json --write
        language: node
        types_or:
          - css
          - html
          - javascript
          - json
          - jsx
          - markdown
          - scss
          - ts
          - tsx
          - yaml
        exclude: ^(docker-)?compose\.ya?ml$
        additional_dependencies:
          - prettier@latest
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
        name: ruff-check
        language: docker_image
        entry: ghcr.io/astral-sh/ruff
        args:
          - check
          - --fix
        files: '.*\.py$'
      - id: ruff-format
        name: ruff-format
        language: docker_image
        entry: ghcr.io/astral-sh/ruff
        args:
          - format
        files: '.*\.py$'
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: shellcheck
      - id: shfmt
        stages:
          - pre-commit
        args:
          - -w
          - -s
          - -i
          - "4"
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
        language: docker_image
      - id: terraform_docs
        language: docker_image
        args:
          - --args=--sort-by-required
  - repo: local
    hooks:
      - id: just
        name: just
        language: system
        entry: just --fmt --unstable
        files: ^justfile$
        pass_filenames: false
        types:
          - file
  - repo: local
    hooks:
      - id: actionlint
        name: actionlint
        description: Static checker for GitHub Actions workflow files
        language: docker_image
        entry: rhysd/actionlint:latest
        args:
          - -verbose
        files: ^\.github/workflows/.*\.(yml|yaml)$
        stages:
          - pre-commit
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
  - repo: local
    hooks:
      - id: taplo-format
        name: taplo-format
        language: docker_image
        entry: tamasfe/taplo:0.10.0
        args:
          - fmt
        files: '.*\.toml$'
  - repo: https://github.com/instrumentl/pre-commit-just
    rev: v0.1
    hooks:
      - id: format-justfile
