set shell := ["bash", "-uec"]

[group('maint')]
default:
    @just --list

[group('maint')]
pre-commit:
    pre-commit install --config .pre-commit-config.yaml

[group('maint')]
fmt:
    #!/usr/bin/env bash
    if ! just fmt; then
        echo "First fmt attempt failed, trying again..."
        just fmt
    fi
