default:
    @just --list

setup:
    bash -xe setup

test:
    cd '{{ .Module }}/{{ .ModuleConsumer }}' && dagger call container-echo --string-arg hello

functions:
    cd '{{ .Module }}/{{ .ModuleConsumer }}' && dagger functions
