#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

rm -rf {{ .Module }}
rm -rf {{ .ModuleConsumer }}

dagger init --sdk=go --source=./dagger
mkdir -p {{ .Module }}
cd {{ .Module }}
dagger init --sdk=go --source=.
dagger install ..
