#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

rm -rf {{ .Module }}
mkdir {{ .Module }}
cd {{ .Module }}
git init
dagger init --sdk=go --source=.
git add -A
git commit -am "boilerplate dagger module"
mkdir -p {{ .ModuleConsumer }}
echo /{{ .ModuleConsumer }} >>.gitignore
git add .gitignore
git commit -am "ignore test app in {{ .Module }} repo"
cd {{ .ModuleConsumer }}
dagger init --sdk=go --source=./dagger
dagger install ..
cd ../..
patch --forward --batch --directory="{{ .Module }}" --input={{ outputFolder }}/{{ .Module }}.patch
patch --forward --batch --directory="{{ .Module }}/{{ .ModuleConsumer }}/dagger" --input={{ outputFolder }}/{{ .ModuleConsumer }}.patch
