set shell := ["bash", "-uec"]

default:
    @just --list

test: setup
    incus exec {{.OutputImage}} -- cat /etc/os-release

image:
    packer init .
    packer build ubuntu.pkr.hcl

setup: image
    terraform init
    terraform plan -out=tfplan
    terraform apply tfplan
    incus ls {{.OutputImage}}
    incus exec {{.OutputImage}} -- curl --version

teardown:
    terraform destroy -auto-approve

fmt:
    shfmt -w -s -i 4 *.sh
    packer fmt -recursive .
    terraform fmt .
    prettier --ignore-path=.prettierignore --config=.prettierrc.json --write .
    just --unstable --fmt
